name: Build and Push Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t orathaisu/hello-python:latest .
          docker tag orathaisu/hello-python:latest orathaisu/hello-python:${{ github.sha }}

      - name: Push Docker images
        run: |
          docker push orathaisu/hello-python:latest
          docker push orathaisu/hello-python:${{ github.sha }}

      - name: Replace image tag in deployment.yaml
        run: sed -i "s|REPLACE_TAG|${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit updated deployment.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add k8s/deployment.yaml
          git commit -m "🚀 Deploy image ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
